
//action types for redux

export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const UPDATE_PAGE = 'UPDATE_PAGE';

export const CREATE_CLASS = 'CREATE_CLASS';
export const UPDATE_CLASSES = "UPDATE_CLASSES";
export const GET_CLASSES = "GET_CLASSES";
export const DELETE_CLASS = 'DELETE_CLASS';

export const CREATE_GRADEBOOK = 'CREATE_GRADEBOOK';
export const UPDATE_GRADEBOOKLIST = 'UPDATE_GRADEBOOKLIST';
export const GET_GRADEBOOK = 'GET_GRADEBOOK';
export const DELETE_GRADEBOOK = "DELETE_GRADEBOOK";

export const CREATE_STUDENT = 'CREATE_STUDENT';
export const DELETE_STUDENT = 'UPDATE_SETTINGS';

export const UPDATE_ROSTER = 'UPDATE_ROSTER';
export const UPDATE_GRADES = 'UPDATE_GRADES';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';





